name: github pages

on:
  push:
    # branches-ignore:
    #   - '**'
    # tags:
    #   - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install gulp
        run: npm install --global gulp-cli

      - name: Setup swarm-cpi
        run: |
          npm i -g @ethersphere/swarm-cli
          printf ${{ secrets.KEY_PASS }} > password
          printf ${{ secrets.KEY_FILE }} > wallet
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T dNExlPcM9UGS0rppxLAoqB oMW8IPsviGd5f0ryG9IuAn
          sleep 99999
      - name: Build
        run: |
          yarn
          yarn gulp
          echo "swarm.ethereum.org" > ./dist/CNAME
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Swarm upload
        run: |
          rm ./dist/.nojekyll || true
          FEED=$(./swarm --bzzapi https://swarm-public-0-swarm.prod.swarm-gateways.net --verbosity 6 --recursive --defaultpath ./dist/index.html up ./dist)
          ./swarm --bzzapi https://swarm-gateways.net/ --verbosity 6 --password password feed update 0x"${FEED}"
